arguments:
  format: json
git_services:
- host: github.com
  repos:
  - hacbs-contract/.github
  - hacbs-contract/chains
  - hacbs-contract/ec-cli
  - hacbs-contract/ec-cookbook
  - hacbs-contract/ec-policies
  - hacbs-contract/enterprise-contract-controller
  - hacbs-contract/golden-container
  - hacbs-contract/hacbs-contract.github.io
  - hacbs-contract/hacks
  - hacbs-contract/infra-deployments-ci
  - hacbs-contract/tekton-catalag
  - redhat-appstudio/book
  - redhat-appstudio/build-definitions
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  #- renovatebot/renovate
  - tektoncd/chains
  token: "${GITHUB_TOKEN}"
  type: github
